version: "3.8"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    expose:
      - 3000
    volumes:
      - ".:/app:rw"
    command: serve build
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=connect_engage.voldemort.wtf
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=connect-engage.voldemort.wtf
      - LETSENCRYPT_EMAIL=kunalsolanke1000@gmail.com
      - REACT_APP_ENV=production
      - REACT_APP_BACKEND=1
networks:
  default:
    external:
      name: nginx-proxy
