version: "3.8"

services:
  web:
    image: node:14-alpine
    ports:
      - "3000:3000"
    expose:
      - 3000
      - 5000
    volumes:
      - ".:/app:rw"
    command: sh -c "cd /app &&yarn global add serve&& serve -s build"
    env_file:
      - .env
    environment:
      - VIRTUAL_HOST=connect-engage.voldemort.wtf
      - VIRTUAL_PORT=5000
      - LETSENCRYPT_HOST=connect-engage.voldemort.wtf
      - LETSENCRYPT_EMAIL=kunalsolanke1000@gmail.com
      - REACT_APP_ENV=production
      - REACT_APP_BACKEND=1
      - REACT_APP_TURN_URI=turn:20.102.73.48:3479?transport=tcp
  s
networks:
  default:
    external:
      name: nginx-proxy
~                                                                                                                                                                                             
~                                                                                                                                                                                             
~                                                                                                                                                                                             
~                                                                                                                                                                                             
~                                                                                                                                                                                             
~                                                                                                                                                                                             
~                                                                                                                                                                                             
"docker-compose.yaml" 40L,