version: "3.8"
services:
  db:
    image: mongo
    restart: unless-stopped
    container_name: mongodb_engage2021
    volumes:
      - dbdata:/data/db
    expose:
      - 27017

  web:
    build: .
    image: engage2021/dev
    container_name: engage2021
    restart: unless-stopped
    env_file: .env
    expose:
      - 3000
    ports:
      - 5000:3000
    depends_on:
      - db
      - redis
    volumes:
      - .:/code
    command: sh -c "/entrypoint"
    environment:
      - MONGO_URI=mongodb://mongodb_engage2021:27017/engage2021
      - WAIT_HOSTS=mongodb_engage2021:27017
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=10
      - WAIT_HOST_CONNECT_TIMEOUT=30
      - VIRTUAL_HOST=engage-backend.voldemort.wtf
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=engage-backend.voldemort.wtf
      - LETSENCRYPT_EMAIL=kunalsolanke1000@gmail.com
      - NODE_ENV=production

  redis:
    restart: unless-stopped
    image: redis:alpine
    ports:
      - "6379:6379"

volumes:
  dbdata:

networks:
  default:
    external:
      name: nginx-proxy
